// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using MyUniversalWindows10App;

namespace MyUniversalWindows10App
{
    public partial class SNEKPrepService : ServiceClient<SNEKPrepService>, ISNEKPrepService
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IConference _conference;
        
        public virtual IConference Conference
        {
            get { return this._conference; }
        }
        
        private ISessions _sessions;
        
        public virtual ISessions Sessions
        {
            get { return this._sessions; }
        }
        
        private ISpeakers _speakers;
        
        public virtual ISpeakers Speakers
        {
            get { return this._speakers; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        public SNEKPrepService()
            : base()
        {
            this._conference = new Conference(this);
            this._sessions = new Sessions(this);
            this._speakers = new Speakers(this);
            this._baseUri = new Uri("https://snekprepservice.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SNEKPrepService(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._conference = new Conference(this);
            this._sessions = new Sessions(this);
            this._speakers = new Speakers(this);
            this._baseUri = new Uri("https://snekprepservice.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SNEKPrepService(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._conference = new Conference(this);
            this._sessions = new Sessions(this);
            this._speakers = new Speakers(this);
            this._baseUri = new Uri("https://snekprepservice.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SNEKPrepService(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SNEKPrepService(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the SNEKPrepService class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public SNEKPrepService(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
