// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using MyUniversalWindows10App.Models;
using Newtonsoft.Json.Linq;

namespace MyUniversalWindows10App.Models
{
    public static partial class SpeakerCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Speaker> DeserializeJson(JToken inputObject)
        {
            IList<Speaker> deserializedObject = new List<Speaker>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Speaker speaker = new Speaker();
                speaker.DeserializeJson(iListValue);
                deserializedObject.Add(speaker);
            }
            return deserializedObject;
        }
    }
}
